### ISSUE TITLE
Please add OS keywords in our api-docs

### ISSUE THREAD

**Issue by peripau** [packethost/api-docs#15]
Hi, twice I received an inquiry from a customer looking for "what api keyword should I put for CentOS 7?"

I guess it would be nice if we have a list of our available OS'es included in our api doc so the customer can use it as reference instead of them jumping into livechat to ask what api keyword shall they use (e.g. CentOS 7 is to centos_7). Thanks a bunch!

**Comment by peripau** [comment]
@gtenaschuk have we published this yet? where do we see the updated change once this is pushed?

somewhere in https://www.packet.net/resources/docs/#page:devices,header:devices-operating-systems ?

Let me know. Thanks!

**Comment by jacobsmith928** [comment]
Please check with @ronggur on this.
