### ISSUE TITLE
SSH Keys Documentation

### ISSUE THREAD

**Issue by dkenzox** [packethost/api-docs#3]
Guys, I've added a few lines in there but I can't test it locally and make it look the live version... I'm getting a lot of warnings from the compiler and the layout seems broken:

>Running "aglio:packet" (aglio) task
Transformers.coffee is deprecated, you must replace the :coffee jade filter, with :coffee-script and install jstransformer-coffee-script before you update to jade@2.0.0.
Transformers.stylus is deprecated, to continue using the :stylus jade filter after jade@2.0.0, you will need to install jstransformer-stylus.
Line 320: unexpected header block, expected a group, resource or an action definition, e.g. '# Group <name>', '# <resource name> [<URI>]' or '# <HTTP method> <URI>' (warning code 5)
Line 321: ignoring unrecognized block (warning code 5)
Line 600: message-body asset is expected to be a pre-formatted code block, separate it by a newline and indent every of its line by 8 spaces or 2 tabs (warning code 10)
Line 600: the 204 response MUST NOT include a message-body (warning code 6)
Line 670: unexpected header block, expected a group, resource or an action definition, e.g. '# Group <name>', '# <resource name> [<URI>]' or '# <HTTP method> <URI>' (warning code 5)
Line 671: ignoring unrecognized block (warning code 5)
Line 674: unexpected header block, expected a group, resource or an action definition, e.g. '# Group <name>', '# <resource name> [<URI>]' or '# <HTTP method> <URI>' (warning code 5)
Line 675: ignoring unrecognized block (warning code 5)
Line 729: unexpected header block, expected a group, resource or an action definition, e.g. '# Group <name>', '# <resource name> [<URI>]' or '# <HTTP method> <URI>' (warning code 5)
Line 730: ignoring unrecognized block (warning code 5)

Something I'm doing wrong or missing ?

**Comment by ronggur** [comment]
@dkenzox, can you try merge branch `master` to your branch? and run `grunt`. The generated api.html file will be in 'dist' directory

I already update https://www.packet.net/dev/api/ with the latest commit from 'master'

**Comment by dkenzox** [comment]
@ronggur If you clone this repository's master branch and run a `grunt` don't you get warnings? that's what I put above.
Regarding the branches, all of my branches come from master: https://github.com/packethost/api-docs/pulls.
The only concern I have is with the warnings you get on `grunt`

**Comment by theunraveler** [comment]
The warnings are fine, I think. They're just coming from the api blueprint compiler, and are warnings about spec violations. As long as the generated HTML looks OK, we're good.

**Comment by dkenzox** [comment]
Actually if you try to test the master branch it doesn't look ok...but it does on our site, so i don't know what is happening there.

**Comment by ronggur** [comment]
@dkenzox do you think it's markdown error? because when I generate template, the projects section is under devices. Shouldn't it be separate?

![screen shot 2015-06-03 at 5 56 29 pm](https://cloud.githubusercontent.com/assets/780024/7958551/b173d162-0a1a-11e5-8b96-2b6bdbeded57.png)

**Comment by dkenzox** [comment]
Actually i don't really know what the problem is...by the warnings the problem is in the `Device->Plans` section, and deleting it make it look good...but on the live site everything is working just fine, so I'm a bit confused there.

**Comment by ronggur** [comment]
Yes, I also find the warning after I re-checkout branch master

**Comment by mustela** [comment]
@ronggur good to close then? Is the doc being generated correctly? Does it have to do with https://github.com/packethost/api-docs/pull/8 ?

**Comment by ronggur** [comment]
I think so, 

That pull request only for templating for https://www.packet.net/dev/api/
