### ISSUE TITLE
What is "X-Consumer-Token" for?

### ISSUE THREAD

**Issue by cholbech** [packethost/api-docs#9]
Question from a customer:

Hi! can you tell me what is "X-Consumer-Token" for? I have seen it None in every request header

**Comment by crunchywelch** [comment]
It is used by us to identify the source of a request, for things like our mobile apps, and external applications that integrate with our API, like terraform, rancher, and docker machine. It is not required, and will generally not be used by end-users who are doing one-off requests. If it is not present then we rate limit the requests. It is also not used for authentication, that is what the end user's auth token is used for.

**Comment by cholbech** [comment]
Thanks @crunchywelch ! Do we need to add this to the API documentation somewhere? Can you do that?

**Comment by theunraveler** [comment]
I don't think we should at this point. Requests will work just fine without `X-Consumer-Token`, but we were talking about doing some rate limiting or something if you don't have one. I think we should wait to document this and/or make it known until we have a clear plan around allowing users to register their app that use our API.
